"""Verify inherited train/validation bytes and passive causal token sources.

Never imports historical experiment code, Torch, or a test/confirmation file.
File identity is checked against fixed author manifests; the raw public
corpus is not independently regenerated by this audit.
"""
from dataclasses import replace
from hashlib import sha256
from itertools import product
from pathlib import Path
import argparse
import json
import sys

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT/'experiments/next_token'))
from causal_tokens import TokenSources, TokenWindow

OUTPUT = ROOT/'evidence/minimal/FP_NEXT_TOKEN_DATA_ENTRY.json'
VOCAB, EOT = 50257, 50256
FILES = {
    'train': (180000000, '7cabea904b3a24958d1e3fcd34f7967a52bc4d11a6ef42b3e2842fa9b816facd'),
    'val': (2000000, 'fe2ce7174972d67b4be62a189f600491dae40cc90e7a0226f1178c8e122b2cb3'),
}


def refuses(function):
    try:
        function()
    except ValueError:
        return
    raise AssertionError('malformed token source accepted')


def exhaustive():
    windows = atoms = perturbed = 0
    for word in product(range(3), repeat=5):
        for context in (1, 2, 3):
            schema = TokenSources(3, context)
            for position in range(6):
                actual = schema.window(word, position)
                expected = tuple(word[position-lag] if position >= lag else 3 for lag in range(1, context+1))
                assert actual.past == expected
                for lag in range(1, context+1):
                    assert sum(actual.atom(lag, token) for token in range(4)) == 1
                    for token in range(4):
                        assert actual.atom(lag, token) == int(expected[lag-1] == token)
                        atoms += 1
                # Change every current/future token. The full source point,
                # including its position and missing-history pattern, is equal.
                changed = word[:position]+tuple((v+1) % 3 for v in word[position:])
                assert schema.window(changed, position) == actual
                windows += 1
                perturbed += int(position < len(word))
    empty = TokenSources(3, 2).window((), 0)
    assert empty.past == (3, 3) and empty.atom(1, 0) == 0
    assert TokenSources(3, 2).window((0,), 1).atom(1, 0) == 1
    for args in ((0, 1), (3, 0), (True, 2), (3, 1.0)):
        refuses(lambda: TokenSources(*args))
    for position in (-1, True, 1.0, 2):
        refuses(lambda: TokenSources(3, 2).window((0,), position))
    for value in (1.5, True, np.bool_(True), -1, 3):
        refuses(lambda: TokenSources(3, 2).window((value,), 1))
    refuses(lambda: replace(empty, past=(0, 3)))
    refuses(lambda: TokenWindow(TokenSources(3, 2), 1, (3, 3)))
    for pair in ((0, 0), (3, 0), (1, 4), (True, 0), (1, True)):
        refuses(lambda: empty.atom(*pair))
    return dict(complete_five_token_histories=3**5, windows=windows, exact_atom_checks=atoms,
        current_and_future_perturbations=perturbed, padding_distinct_from_token_zero=True,
        strict_shape_index_and_padding_refusals=True)


def verify_file(root, split):
    # Only these fixed two filenames can be read. In particular no historical
    # test or confirmation data are opened, hashed, sampled or scored.
    count, expected_hash = FILES[split]
    path = root/(split+'.bin')
    assert path.stat().st_size == 2*count
    digest = sha256()
    low, high, end_count, offset, first_end = 65535, 0, 0, 0, None
    with path.open('rb') as handle:
        while block := handle.read(2 << 20):
            assert len(block) % 2 == 0
            digest.update(block)
            values = np.frombuffer(block, dtype='<u2')
            low, high = min(low, int(values.min())), max(high, int(values.max()))
            assert high < VOCAB
            ends = np.flatnonzero(values == EOT)
            if first_end is None and len(ends):
                first_end = offset+int(ends[0])
            end_count += len(ends)
            offset += len(values)
    assert offset == count and digest.hexdigest() == expected_hash
    tokens = np.memmap(path, mode='r', dtype='<u2')
    positions = sorted({0, 1, 511, 512, count-1, first_end, first_end+1})
    checks = 0
    for context in (1, 32, 512):
        schema = TokenSources(VOCAB, context)
        for position in positions:
            window = schema.window(tokens, position)
            for lag, token in enumerate(window.past, 1):
                expected = int(tokens[position-lag]) if position >= lag else VOCAB
                assert token == expected and window.atom(lag, token) == 1
                assert window.atom(lag, (token+1) % (VOCAB+1)) == 0
                checks += 1
    # EOT stays an ordinary observed source token; there is no implicit reset.
    assert TokenSources(VOCAB, 2).window(tokens, first_end+1).past[0] == EOT
    return dict(bytes=path.stat().st_size, tokens=count, sha256=expected_hash,
        token_id_range=[low, high], eot_count=int(end_count), final_token_is_eot=bool(tokens[-1] == EOT),
        context_lengths=[1, 32, 512], audited_positions=len(positions), exact_real_lag_checks=checks)


def main(root):
    manifest = json.loads((root/'manifest.json').read_text(encoding='utf-8'))
    assert manifest['repo'] == 'HuggingFaceFW/fineweb-edu' and manifest['name'] == 'sample-10BT'
    assert manifest['resolved_revision'] == '87f09149ef4734204d70ed1d046ddc9ca3f2b8f9'
    assert manifest['tokenizer'] == 'gpt2' and manifest['tokenizer_vocab'] == VOCAB and manifest['eot_token'] == EOT
    for split, (count, digest) in FILES.items():
        assert manifest['files'][split] == dict(bytes=2*count, tokens=count, sha256=digest)
    result = dict(status='PASS_NEXT_TOKEN_DATA_ENTRY', source={
        'repo': manifest['repo'], 'subset': manifest['name'], 'revision': manifest['resolved_revision'],
        'local_root': str(root.resolve()), 'format': 'little-endian uint16', 'tokenizer': 'gpt2',
        'vocabulary': VOCAB, 'eot': EOT, 'provenance': 'historical author manifest and inspected preparation recipe; no independent full raw-corpus reconstruction'},
        files={split: verify_file(root, split) for split in FILES}, causal_sources=exhaustive(),
        source_contract=dict(padding_id=VOCAB, context_order='lag 1 first; prediction at position t uses only indices < t',
            eot_handling='retained as an ordinary observed token; no implicit context reset',
            width_512_indexed_atoms=TokenSources(VOCAB, 512).source_count),
        historical_test_and_confirmation_files_opened=False, model_scores_computed=False,
        scope='file identity, complete token ranges and passive causal source values; no split independence, statistical law, model or Runtime authority')
    assert 'torch' not in sys.modules
    return result


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--data-root', type=Path, required=True)
    parser.add_argument('--write', action='store_true')
    args = parser.parse_args()
    result = main(args.data_root)
    if args.write:
        OUTPUT.write_text(json.dumps(result, indent=2)+'\n', encoding='utf-8')
    print(json.dumps(result, indent=2))
